// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXU4Ox0-hPFyuBY6vSZ0CZyK8MpHI49Zs',
    appId: '1:419276524336:web:3c1003274c5638960cd6f5',
    messagingSenderId: '419276524336',
    projectId: 'tugas2kelompok3',
    authDomain: 'tugas2kelompok3.firebaseapp.com',
    storageBucket: 'tugas2kelompok3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmfvAjLwB7t8N0VnOx1YwvZMDgfseH6Nk',
    appId: '1:419276524336:android:3c8a7a26e059eff80cd6f5',
    messagingSenderId: '419276524336',
    projectId: 'tugas2kelompok3',
    storageBucket: 'tugas2kelompok3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByOCnOvnEWvzN1bzCOeU7jjPWpJROJnLw',
    appId: '1:419276524336:ios:f58dd5fc9961c91a0cd6f5',
    messagingSenderId: '419276524336',
    projectId: 'tugas2kelompok3',
    storageBucket: 'tugas2kelompok3.appspot.com',
    iosClientId: '419276524336-lue4kppuuu473r8e7v3qihif04ihkdfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugas2kelompok3',
  );
}
